[build]
target = "x86_64-unknown-none"

# Override host linker for build scripts
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

# Kernel target
[target.x86_64-unknown-none]
runner = "bootimage runner"
linker = "rust-lld.exe"
rustflags = [
    "-C", "link-arg=-Tkernel/src/arch/linker.ld",
    "-C", "relocation-model=static",
    "-C", "code-model=large",
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=0x1000",
]

# Bootloader target
[target.x86_64-unknown-uefi]
linker = "rust-lld.exe"
rustflags = [
    "-C", "link-arg=/subsystem:efi_application",
    "-C", "link-arg=/entry:efi_main",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
